local F, C = unpack(select(2, ...))

C.themes["Blizzard_FlightMap"] = function()
	F.SetBD(FlightMapFrame, -5, 5, 5, -5)
	F.ReskinClose(FlightMapFrameCloseButton)
	FlightMapFrameLeftBorder:Hide()
	FlightMapFrameRightBorder:Hide()
	FlightMapFrameTopBorder:Hide()
	FlightMapFrameBottomBorder:Hide()
	FlightMapFrameBotLeftCorner:Hide()
	FlightMapFrameBotRightCorner:Hide()
	FlightMapFrameTopRightCorner:Hide()
	FlightMapFramePortrait:Hide()
	FlightMapFramePortraitFrame:Hide()
	FlightMapFrameTitleBg:Hide()
	FlightMapFrame.BorderFrame.TopBorder:Hide()
end