if IsAddOnLoaded("Aurora") then
	local F = unpack(Aurora)
	F.ReskinCheck(QNOchk_Switch)
	F.ReskinCheck(QNOchk_Instance)
	F.ReskinCheck(QNOchk_Raid)
	F.ReskinCheck(QNOchk_Party)
	F.ReskinCheck(QNOchk_Solo)
	F.ReskinCheck(QNOchk_Sound)
	F.ReskinCheck(QNOchk_Debug)
	F.ReskinCheck(QNOchk_NoDetail)
	F.ReskinCheck(QNOchk_CompleteX)
elseif IsAddOnLoaded("NDui") then
	local B = unpack(NDui)
	B.CreateCB(QNOchk_Switch)
	B.CreateCB(QNOchk_Instance)
	B.CreateCB(QNOchk_Raid)
	B.CreateCB(QNOchk_Party)
	B.CreateCB(QNOchk_Solo)
	B.CreateCB(QNOchk_Sound)
	B.CreateCB(QNOchk_Debug)
	B.CreateCB(QNOchk_NoDetail)
	B.CreateCB(QNOchk_CompleteX)
end