local F, C = unpack(select(2, ...))

tinsert(C.themes["AuroraClassic"], function()
	select(18, ItemTextFrame:GetRegions()):Hide()
	InboxFrameBg:Hide()
	ItemTextPrevPageButton:GetRegions():Hide()
	ItemTextNextPageButton:GetRegions():Hide()
	ItemTextMaterialTopLeft:SetAlpha(0)
	ItemTextMaterialTopRight:SetAlpha(0)
	ItemTextMaterialBotLeft:SetAlpha(0)
	ItemTextMaterialBotRight:SetAlpha(0)

	F.ReskinPortraitFrame(ItemTextFrame, true)
	F.ReskinScroll(ItemTextScrollFrameScrollBar)
	F.ReskinArrow(ItemTextPrevPageButton, "left")
	F.ReskinArrow(ItemTextNextPageButton, "right")
	ItemTextScrollFrameScrollBar.Middle:Hide()
	ItemTextScrollFrameScrollBar.Background:Hide()
	ItemTextScrollFrameScrollBar.Top:Hide()
	ItemTextScrollFrameScrollBar.Bottom:Hide()
	ItemTextFramePageBg:SetAlpha(0)
	ItemTextPageText:SetTextColor(1, 1, 1)
	ItemTextPageText.SetTextColor = F.dummy
end)